bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost user=rdovgii password=123456 dbname=restapi_dev sslmode=disable"
session_key = "mYq3t6v9y$B&E)H@McQfTjWnZr4u7x!z%C*F-JaNdRgUkXp2s5v8y/B?D(G+KbPe"